### ISSUE TITLE
Error: Cannot find module 'config'

### ISSUE THREAD

**Issue by nishu-ptg** [kinshuk-kataria/mern-ecommerce#15]
hello, backend is not running because config is missing due to ignored in git, which is understandable, but need to know what is supposed to be in there, could you please share the 'template(s)' for config dir (except the actual values of course)? thanks!

**Comment by kinshuk-kataria** [comment]
The config package was previously utilized for managing environment variables. However, it is no longer in use, and you can disregard it. The current approach involves employing the dotenv package to handle environment variables instead.
